// oa_admin/src/components/AttendanceDetail.vue
<template>
  <div class="attendance-detail">
    <div class="detail-header">
      <h2>考勤详情</h2>
      <button class="btn btn-secondary" @click="$emit('close')">返回</button>
    </div>

    <div v-if="loading" class="loading-state">
      <div class="spinner"></div>
      <p>加载中...</p>
    </div>

    <template v-else-if="detail">
      <!-- 基本信息卡片 -->
      <div class="info-card">
        <div class="card-header">
          <h3>{{ formatDate(detail.attend_date) }} 考勤记录</h3>
          <span :class="['status-badge', getStatusClass(detail.status)]">
            {{ getStatusText(detail.status) }}
          </span>
        </div>

        <div class="info-grid">
          <div class="info-item">
            <label>员工姓名</label>
            <span>{{ detail.user_name }}</span>
          </div>
          <div class="info-item">
            <label>部门</label>
            <span>{{ detail.dept_name }}</span>
          </div>
          <div class="info-item">
            <label>职位</label>
            <span>{{ detail.position_name }}</span>
          </div>
          <div class="info-item">
            <label>上班打卡</label>
            <span>{{ formatTime(detail.clock_in_time) }}</span>
          </div>
          <div class="info-item">
            <label>下班打卡</label>
            <span>{{ formatTime(detail.clock_out_time) }}</span>
          </div>
          <div class="info-item">
            <label>工作时长</label>
            <span>{{ detail.work_hours || 0 }}小时</span>
          </div>
          <div class="info-item">
            <label>打卡地点</label>
            <span>{{ detail.clock_in_location || detail.clock_out_location || '--' }}</span>
          </div>
        </div>
      </div>

      <!-- 工资影响卡片 -->
      <div class="info-card" v-if="detail.salaryImpact">
        <div class="card-header">
          <h3>工资影响</h3>
        </div>
        <div :class="['salary-impact', detail.salaryImpact.type]">
          <div class="impact-icon">
            {{ detail.salaryImpact.type === 'bonus' ? '💰' : detail.salaryImpact.type === 'penalty' ? '⚠️' : '✅' }}
          </div>
          <div class="impact-info">
            <div class="impact-amount">
              {{ detail.salaryImpact.type === 'bonus' ? '+' : '' }}{{ detail.salaryImpact.amount }}元
            </div>
            <div class="impact-desc">{{ detail.salaryImpact.description }}</div>
          </div>
        </div>
      </div>

      <!-- 处罚记录卡片 -->
      <div class="info-card" v-if="detail.penalties && detail.penalties.length > 0">
        <div class="card-header">
          <h3>处罚记录</h3>
        </div>
        <div class="penalty-list">
          <div v-for="penalty in detail.penalties" :key="penalty.id" class="penalty-item">
            <div class="penalty-info">
              <div class="penalty-type">{{ getPenaltyTypeText(penalty.type) }}</div>
              <div class="penalty-desc">{{ penalty.description }}</div>
              <div class="penalty-amount">处罚金额: {{ penalty.amount }}元</div>
            </div>
            <div class="penalty-status">
              <span :class="['status-badge', getPenaltyStatusClass(penalty.status)]">
                {{ getPenaltyStatusText(penalty.status) }}
              </span>
              <button
                v-if="penalty.status === 'pending'"
                class="btn btn-primary btn-sm"
                @click="openAppealDialog(penalty)"
              >
                申诉
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- 申诉记录卡片 -->
      <div class="info-card" v-if="detail.appeals && detail.appeals.length > 0">
        <div class="card-header">
          <h3>申诉记录</h3>
        </div>
        <div class="appeal-list">
          <div v-for="appeal in detail.appeals" :key="appeal.id" class="appeal-item">
            <div class="appeal-info">
              <div class="appeal-type">{{ getAppealTypeText(appeal.type) }}</div>
              <div class="appeal-reason">{{ appeal.reason }}</div>
              <div class="appeal-time">提交时间: {{ formatDateTime(appeal.createTime) }}</div>
            </div>
            <div class="appeal-status">
              <span :class="['status-badge', getAppealStatusClass(appeal.status)]">
                {{ getAppealStatusText(appeal.status) }}
              </span>
              <div v-if="appeal.approveRemark" class="approve-remark">
                审批备注: {{ appeal.approveRemark }}
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- 操作按钮 -->
      <div class="action-buttons">
        <button
          v-if="canAppeal"
          class="btn btn-primary"
          @click="openAppealDialog(null)"
        >
          提交申诉
        </button>
        <button
          v-if="hasPendingAppeals"
          class="btn btn-warning"
          @click="goToApproval"
        >
          前往审批
        </button>
      </div>
    </template>

    <!-- 申诉对话框 -->
    <div v-if="showAppealDialog" class="modal-overlay" @click.self="closeAppealDialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3>提交考勤申诉</h3>
          <button class="btn-close" @click="closeAppealDialog">&times;</button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label>申诉类型</label>
            <select v-model="appealForm.type" class="form-control">
              <option value="late">迟到申诉</option>
              <option value="early">早退申诉</option>
              <option value="absent">缺勤申诉</option>
            </select>
          </div>
          <div class="form-group">
            <label>申诉原因</label>
            <textarea
              v-model="appealForm.reason"
              class="form-control"
              rows="4"
              placeholder="请详细说明申诉原因..."
            ></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" @click="closeAppealDialog">取消</button>
          <button class="btn btn-primary" @click="submitAppeal" :disabled="submitting">
            {{ submitting ? '提交中...' : '提交申诉' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { getAttendanceDetail, submitAttendanceAppeal } from '../api';
import { Alert } from '../store';

const props = defineProps<{
  attendanceId: string;
}>();

const emit = defineEmits(['close', 'goToApproval']);

const loading = ref(true);
const detail = ref<any>(null);
const showAppealDialog = ref(false);
const submitting = ref(false);
const appealForm = ref({
  type: 'late',
  reason: ''
});

// 计算属性
const canAppeal = computed(() => {
  if (!detail.value) return false;
  const hasPendingPenalty = detail.value.penalties?.some((p: any) => p.status === 'pending');
  const hasNoPendingAppeal = !detail.value.appeals?.some((a: any) => a.status === 'pending');
  return hasPendingPenalty && hasNoPendingAppeal;
});

const hasPendingAppeals = computed(() => {
  if (!detail.value) return false;
  return detail.value.appeals?.some((a: any) => a.status === 'pending');
});

// 加载数据
const loadDetail = async () => {
  loading.value = true;
  try {
    const res = await getAttendanceDetail(props.attendanceId);
    detail.value = res;
  } catch (error: any) {
    Alert.alert('错误', error.message || '加载考勤详情失败');
  } finally {
    loading.value = false;
  }
};

// 打开申诉对话框
const openAppealDialog = (penalty: any) => {
  if (penalty) {
    appealForm.value.type = penalty.type;
  }
  showAppealDialog.value = true;
};

// 关闭申诉对话框
const closeAppealDialog = () => {
  showAppealDialog.value = false;
  appealForm.value = { type: 'late', reason: '' };
};

// 提交申诉
const submitAppeal = async () => {
  if (!appealForm.value.reason.trim()) {
    Alert.alert('提示', '请填写申诉原因');
    return;
  }

  submitting.value = true;
  try {
    await submitAttendanceAppeal({
      attendance_id: props.attendanceId,
      appeal_type: appealForm.value.type,
      reason: appealForm.value.reason
    });
    Alert.alert('成功', '申诉提交成功，等待审批');
    closeAppealDialog();
    loadDetail(); // 重新加载数据
  } catch (error: any) {
    Alert.alert('错误', error.message || '申诉提交失败');
  } finally {
    submitting.value = false;
  }
};

// 前往审批
const goToApproval = () => {
  emit('goToApproval');
};

// 格式化日期
const formatDate = (date: string) => {
  if (!date) return '--';
  return new Date(date).toLocaleDateString('zh-CN');
};

// 格式化时间
const formatTime = (time: string) => {
  if (!time) return '--:--';
  return new Date(time).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' });
};

// 格式化日期时间
const formatDateTime = (datetime: string) => {
  if (!datetime) return '--';
  return new Date(datetime).toLocaleString('zh-CN');
};

// 获取状态样式类
const getStatusClass = (status: string) => {
  const map: Record<string, string> = {
    normal: 'status-success',
    late: 'status-warning',
    early: 'status-warning',
    late_early: 'status-danger',
    absent: 'status-danger',
    out_of_range: 'status-info'
  };
  return map[status] || 'status-default';
};

// 获取状态文本
const getStatusText = (status: string) => {
  const map: Record<string, string> = {
    normal: '正常',
    late: '迟到',
    early: '早退',
    late_early: '迟到+早退',
    absent: '缺勤',
    out_of_range: '外勤打卡'
  };
  return map[status] || status;
};

// 获取处罚类型文本
const getPenaltyTypeText = (type: string) => {
  const map: Record<string, string> = {
    late: '迟到处罚',
    early: '早退处罚',
    absent: '缺勤处罚',
    overtime: '加班奖励'
  };
  return map[type] || type;
};

// 获取处罚状态样式类
const getPenaltyStatusClass = (status: string) => {
  const map: Record<string, string> = {
    pending: 'status-warning',
    appealed: 'status-info',
    approved: 'status-success',
    rejected: 'status-danger'
  };
  return map[status] || 'status-default';
};

// 获取处罚状态文本
const getPenaltyStatusText = (status: string) => {
  const map: Record<string, string> = {
    pending: '待处理',
    appealed: '已申诉',
    approved: '已通过',
    rejected: '已拒绝'
  };
  return map[status] || status;
};

// 获取申诉类型文本
const getAppealTypeText = (type: string) => {
  const map: Record<string, string> = {
    late: '迟到申诉',
    early: '早退申诉',
    absent: '缺勤申诉'
  };
  return map[type] || type;
};

// 获取申诉状态样式类
const getAppealStatusClass = (status: string) => {
  const map: Record<string, string> = {
    pending: 'status-warning',
    approved: 'status-success',
    rejected: 'status-danger'
  };
  return map[status] || 'status-default';
};

// 获取申诉状态文本
const getAppealStatusText = (status: string) => {
  const map: Record<string, string> = {
    pending: '待审批',
    approved: '已通过',
    rejected: '已拒绝'
  };
  return map[status] || status;
};

onMounted(() => {
  loadDetail();
});
</script>

<style scoped>
.attendance-detail {
  padding: 20px;
}

.detail-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.info-card {
  background: #fff;
  border-radius: 8px;
  padding: 20px;
  margin-bottom: 20px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
  padding-bottom: 12px;
  border-bottom: 1px solid #eee;
}

.info-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 16px;
}

.info-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.info-item label {
  font-size: 12px;
  color: #666;
}

.info-item span {
  font-size: 14px;
  font-weight: 500;
}

.status-badge {
  padding: 4px 8px;
  border-radius: 4px;
  font-size: 12px;
  font-weight: 500;
}

.status-success { background: #e6f7e6; color: #52c41a; }
.status-warning { background: #fff7e6; color: #faad14; }
.status-danger { background: #fff2e8; color: #ff4d4f; }
.status-info { background: #e6f7ff; color: #1890ff; }

.salary-impact {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 16px;
  border-radius: 8px;
}

.salary-impact.bonus { background: #f6ffed; }
.salary-impact.penalty { background: #fff2e8; }
.salary-impact.normal { background: #f0f0f0; }

.impact-icon {
  font-size: 32px;
}

.impact-amount {
  font-size: 20px;
  font-weight: bold;
}

.salary-impact.bonus .impact-amount { color: #52c41a; }
.salary-impact.penalty .impact-amount { color: #ff4d4f; }

.penalty-list, .appeal-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.penalty-item, .appeal-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px;
  background: #f9f9f9;
  border-radius: 6px;
}

.penalty-type, .appeal-type {
  font-weight: 500;
  margin-bottom: 4px;
}

.penalty-desc, .appeal-reason {
  font-size: 13px;
  color: #666;
  margin-bottom: 4px;
}

.penalty-amount, .appeal-time {
  font-size: 12px;
  color: #999;
}

.approve-remark {
  font-size: 12px;
  color: #666;
  margin-top: 4px;
}

.action-buttons {
  display: flex;
  gap: 12px;
  margin-top: 20px;
}

.btn {
  padding: 8px 16px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
}

.btn-primary { background: #1890ff; color: #fff; }
.btn-secondary { background: #f0f0f0; color: #333; }
.btn-warning { background: #faad14; color: #fff; }
.btn-sm { padding: 4px 8px; font-size: 12px; }

.loading-state {
  text-align: center;
  padding: 40px;
}

.spinner {
  width: 40px;
  height: 40px;
  border: 4px solid #f3f3f3;
  border-top: 4px solid #1890ff;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin: 0 auto 16px;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-content {
  background: #fff;
  border-radius: 8px;
  width: 500px;
  max-width: 90%;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 20px;
  border-bottom: 1px solid #eee;
}

.modal-body {
  padding: 20px;
}

.modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding: 16px 20px;
  border-top: 1px solid #eee;
}

.form-group {
  margin-bottom: 16px;
}

.form-group label {
  display: block;
  margin-bottom: 8px;
  font-weight: 500;
}

.form-control {
  width: 100%;
  padding: 8px 12px;
  border: 1px solid #d9d9d9;
  border-radius: 4px;
  font-size: 14px;
}

textarea.form-control {
  resize: vertical;
}

.btn-close {
  background: none;
  border: none;
  font-size: 24px;
  cursor: pointer;
  color: #999;
}
</style>

// oa_domes/src/app/attendance-detail.tsx
import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  ActivityIndicator,
  TextInput,
  Modal
} from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { fetchAttendanceDetail, submitAttendanceAppeal } from '../api/services';
import { getCurrentUser } from '../api/session';

export default function AttendanceDetailScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams();
  const [loading, setLoading] = useState(true);
  const [detail, setDetail] = useState<any>(null);
  const [showAppealModal, setShowAppealModal] = useState(false);
  const [appealType, setAppealType] = useState('late');
  const [appealReason, setAppealReason] = useState('');
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    loadDetail();
  }, [id]);

  const loadDetail = async () => {
    setLoading(true);
    try {
      const res = await fetchAttendanceDetail(id as string);
      setDetail(res);
    } catch (error: any) {
      Alert.alert('错误', error.message || '加载考勤详情失败');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmitAppeal = async () => {
    if (!appealReason.trim()) {
      Alert.alert('提示', '请填写申诉原因');
      return;
    }

    setSubmitting(true);
    try {
      await submitAttendanceAppeal({
        attendance_id: id as string,
        appeal_type: appealType,
        reason: appealReason
      });
      Alert.alert('成功', '申诉提交成功，等待审批');
      setShowAppealModal(false);
      setAppealReason('');
      loadDetail();
    } catch (error: any) {
      Alert.alert('错误', error.message || '申诉提交失败');
    } finally {
      setSubmitting(false);
    }
  };

  const formatTime = (time: string) => {
    if (!time) return '--:--';
    return new Date(time).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' });
  };

  const formatDate = (date: string) => {
    if (!date) return '--';
    return new Date(date).toLocaleDateString('zh-CN');
  };

  const getStatusText = (status: string) => {
    const map: Record<string, string> = {
      normal: '正常',
      late: '迟到',
      early: '早退',
      late_early: '迟到+早退',
      absent: '缺勤',
      out_of_range: '外勤打卡'
    };
    return map[status] || status;
  };

  const getStatusColor = (status: string) => {
    if (status === 'normal') return '#10b981';
    if (status.includes('late') || status.includes('early')) return '#f59e0b';
    if (status === 'absent') return '#ef4444';
    return '#6b7280';
  };

  const getPenaltyTypeText = (type: string) => {
    const map: Record<string, string> = {
      late: '迟到处罚',
      early: '早退处罚',
      absent: '缺勤处罚',
      overtime: '加班奖励'
    };
    return map[type] || type;
  };

  const getPenaltyStatusText = (status: string) => {
    const map: Record<string, string> = {
      pending: '待处理',
      appealed: '已申诉',
      approved: '已通过',
      rejected: '已拒绝'
    };
    return map[status] || status;
  };

  const getAppealStatusText = (status: string) => {
    const map: Record<string, string> = {
      pending: '待审批',
      approved: '已通过',
      rejected: '已拒绝'
    };
    return map[status] || status;
  };

  const canAppeal = () => {
    if (!detail) return false;
    const hasPendingPenalty = detail.penalties?.some((p: any) => p.status === 'pending');
    const hasNoPendingAppeal = !detail.appeals?.some((a: any) => a.status === 'pending');
    return hasPendingPenalty && hasNoPendingAppeal;
  };

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#6358ee" />
        <Text style={styles.loadingText}>加载中...</Text>
      </View>
    );
  }

  if (!detail) {
    return (
      <View style={styles.errorContainer}>
        <Text style={styles.errorText}>加载失败</Text>
        <TouchableOpacity style={styles.retryButton} onPress={loadDetail}>
          <Text style={styles.retryButtonText}>重试</Text>
        </TouchableOpacity>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      {/* 头部 */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
          <Feather name="arrow-left" size={24} color="#fff" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>考勤详情</Text>
        <View style={styles.placeholder} />
      </View>

      <ScrollView style={styles.content}>
        {/* 基本信息卡片 */}
        <View style={styles.card}>
          <View style={styles.cardHeader}>
            <Text style={styles.cardTitle}>{formatDate(detail.attend_date)} 考勤记录</Text>
            <View style={[styles.statusBadge, { backgroundColor: getStatusColor(detail.status) + '20' }]}>
              <Text style={[styles.statusText, { color: getStatusColor(detail.status) }]}>
                {getStatusText(detail.status)}
              </Text>
            </View>
          </View>

          <View style={styles.infoGrid}>
            <View style={styles.infoItem}>
              <Text style={styles.infoLabel}>员工姓名</Text>
              <Text style={styles.infoValue}>{detail.user_name}</Text>
            </View>
            <View style={styles.infoItem}>
              <Text style={styles.infoLabel}>部门</Text>
              <Text style={styles.infoValue}>{detail.dept_name}</Text>
            </View>
            <View style={styles.infoItem}>
              <Text style={styles.infoLabel}>上班打卡</Text>
              <Text style={styles.infoValue}>{formatTime(detail.clock_in_time)}</Text>
            </View>
            <View style={styles.infoItem}>
              <Text style={styles.infoLabel}>下班打卡</Text>
              <Text style={styles.infoValue}>{formatTime(detail.clock_out_time)}</Text>
            </View>
            <View style={styles.infoItem}>
              <Text style={styles.infoLabel}>工作时长</Text>
              <Text style={styles.infoValue}>{detail.work_hours || 0}小时</Text>
            </View>
            <View style={styles.infoItem}>
              <Text style={styles.infoLabel}>打卡地点</Text>
              <Text style={styles.infoValue}>{detail.clock_in_location || detail.clock_out_location || '--'}</Text>
            </View>
          </View>
        </View>

        {/* 工资影响卡片 */}
        {detail.salaryImpact && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>工资影响</Text>
            <View style={[
              styles.salaryImpact,
              detail.salaryImpact.type === 'bonus' && styles.salaryBonus,
              detail.salaryImpact.type === 'penalty' && styles.salaryPenalty
            ]}>
              <Text style={styles.impactIcon}>
                {detail.salaryImpact.type === 'bonus' ? '💰' : detail.salaryImpact.type === 'penalty' ? '⚠️' : '✅'}
              </Text>
              <View style={styles.impactInfo}>
                <Text style={[
                  styles.impactAmount,
                  detail.salaryImpact.type === 'bonus' && { color: '#10b981' },
                  detail.salaryImpact.type === 'penalty' && { color: '#ef4444' }
                ]}>
                  {detail.salaryImpact.type === 'bonus' ? '+' : ''}{detail.salaryImpact.amount}元
                </Text>
                <Text style={styles.impactDesc}>{detail.salaryImpact.description}</Text>
              </View>
            </View>
          </View>
        )}

        {/* 处罚记录卡片 */}
        {detail.penalties && detail.penalties.length > 0 && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>处罚记录</Text>
            {detail.penalties.map((penalty: any) => (
              <View key={penalty.id} style={styles.penaltyItem}>
                <View style={styles.penaltyInfo}>
                  <Text style={styles.penaltyType}>{getPenaltyTypeText(penalty.type)}</Text>
                  <Text style={styles.penaltyDesc}>{penalty.description}</Text>
                  <Text style={styles.penaltyAmount}>处罚金额: {penalty.amount}元</Text>
                </View>
                <View style={styles.penaltyStatus}>
                  <View style={[styles.statusBadge, { backgroundColor: penalty.status === 'pending' ? '#fef3c7' : '#e5e7eb' }]}>
                    <Text style={[styles.statusText, { color: penalty.status === 'pending' ? '#d97706' : '#6b7280' }]}>
                      {getPenaltyStatusText(penalty.status)}
                    </Text>
                  </View>
                  {penalty.status === 'pending' && (
                    <TouchableOpacity
                      style={styles.appealButton}
                      onPress={() => {
                        setAppealType(penalty.type);
                        setShowAppealModal(true);
                      }}
                    >
                      <Text style={styles.appealButtonText}>申诉</Text>
                    </TouchableOpacity>
                  )}
                </View>
              </View>
            ))}
          </View>
        )}

        {/* 申诉记录卡片 */}
        {detail.appeals && detail.appeals.length > 0 && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>申诉记录</Text>
            {detail.appeals.map((appeal: any) => (
              <View key={appeal.id} style={styles.appealItem}>
                <View style={styles.appealInfo}>
                  <Text style={styles.appealType}>
                    {appeal.type === 'late' ? '迟到申诉' : appeal.type === 'early' ? '早退申诉' : '缺勤申诉'}
                  </Text>
                  <Text style={styles.appealReason}>{appeal.reason}</Text>
                  <Text style={styles.appealTime}>提交时间: {formatDate(appeal.createTime)}</Text>
                </View>
                <View style={styles.appealStatus}>
                  <View style={[
                    styles.statusBadge,
                    { backgroundColor: appeal.status === 'pending' ? '#fef3c7' : appeal.status === 'approved' ? '#d1fae5' : '#fee2e2' }
                  ]}>
                    <Text style={[
                      styles.statusText,
                      { color: appeal.status === 'pending' ? '#d97706' : appeal.status === 'approved' ? '#059669' : '#dc2626' }
                    ]}>
                      {getAppealStatusText(appeal.status)}
                    </Text>
                  </View>
                  {appeal.approveRemark && (
                    <Text style={styles.approveRemark}>审批备注: {appeal.approveRemark}</Text>
                  )}
                </View>
              </View>
            ))}
          </View>
        )}

        {/* 操作按钮 */}
        <View style={styles.actionButtons}>
          {canAppeal() && (
            <TouchableOpacity
              style={styles.primaryButton}
              onPress={() => setShowAppealModal(true)}
            >
              <Text style={styles.primaryButtonText}>提交申诉</Text>
            </TouchableOpacity>
          )}
        </View>
      </ScrollView>

      {/* 申诉对话框 */}
      <Modal
        visible={showAppealModal}
        transparent={true}
        animationType="slide"
      >
        <View style={styles.modalOverlay}>
          <View style={styles.modalContent}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>提交考勤申诉</Text>
              <TouchableOpacity onPress={() => setShowAppealModal(false)}>
                <Feather name="x" size={24} color="#666" />
              </TouchableOpacity>
            </View>

            <View style={styles.modalBody}>
              <Text style={styles.label}>申诉类型</Text>
              <View style={styles.typeSelector}>
                {['late', 'early', 'absent'].map((type) => (
                  <TouchableOpacity
                    key={type}
                    style={[
                      styles.typeOption,
                      appealType === type && styles.typeOptionActive
                    ]}
                    onPress={() => setAppealType(type)}
                  >
                    <Text style={[
                      styles.typeOptionText,
                      appealType === type && styles.typeOptionTextActive
                    ]}>
                      {type === 'late' ? '迟到' : type === 'early' ? '早退' : '缺勤'}
                    </Text>
                  </TouchableOpacity>
                ))}
              </View>

              <Text style={styles.label}>申诉原因</Text>
              <TextInput
                style={styles.textArea}
                multiline
                numberOfLines={4}
                placeholder="请详细说明申诉原因..."
                value={appealReason}
                onChangeText={setAppealReason}
              />
            </View>

            <View style={styles.modalFooter}>
              <TouchableOpacity
                style={styles.cancelButton}
                onPress={() => setShowAppealModal(false)}
              >
                <Text style={styles.cancelButtonText}>取消</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.submitButton, submitting && styles.submitButtonDisabled]}
                onPress={handleSubmitAppeal}
                disabled={submitting}
              >
                {submitting ? (
                  <ActivityIndicator color="#fff" size="small" />
                ) : (
                  <Text style={styles.submitButtonText}>提交申诉</Text>
                )}
              </TouchableOpacity>
            </View>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    color: '#666',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    color: '#666',
    marginBottom: 12,
  },
  retryButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#6358ee',
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#fff',
    fontWeight: '500',
  },
  header: {
    backgroundColor: '#6358ee',
    paddingTop: 48,
    paddingBottom: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  placeholder: {
    width: 40,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '500',
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  infoItem: {
    width: '48%',
  },
  infoLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
  },
  salaryImpact: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 8,
    backgroundColor: '#f9f9f9',
    marginTop: 12,
  },
  salaryBonus: {
    backgroundColor: '#f0fdf4',
  },
  salaryPenalty: {
    backgroundColor: '#fef2f2',
  },
  impactIcon: {
    fontSize: 32,
    marginRight: 16,
  },
  impactInfo: {
    flex: 1,
  },
  impactAmount: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  impactDesc: {
    fontSize: 13,
    color: '#666',
  },
  penaltyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
    marginTop: 12,
  },
  penaltyInfo: {
    flex: 1,
  },
  penaltyType: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 4,
  },
  penaltyDesc: {
    fontSize: 13,
    color: '#666',
    marginBottom: 4,
  },
  penaltyAmount: {
    fontSize: 12,
    color: '#999',
  },
  penaltyStatus: {
    alignItems: 'flex-end',
    gap: 8,
  },
  appealButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#6358ee',
    borderRadius: 6,
  },
  appealButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
  },
  appealItem: {
    padding: 12,
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
    marginTop: 12,
  },
  appealInfo: {
    marginBottom: 8,
  },
  appealType: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 4,
  },
  appealReason: {
    fontSize: 13,
    color: '#666',
    marginBottom: 4,
  },
  appealTime: {
    fontSize: 12,
    color: '#999',
  },
  appealStatus: {
    alignItems: 'flex-start',
    gap: 4,
  },
  approveRemark: {
    fontSize: 12,
    color: '#666',
  },
  actionButtons: {
    marginTop: 8,
    marginBottom: 32,
  },
  primaryButton: {
    backgroundColor: '#6358ee',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  modalBody: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 8,
    color: '#333',
  },
  typeSelector: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  typeOption: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d9d9d9',
    alignItems: 'center',
  },
  typeOptionActive: {
    borderColor: '#6358ee',
    backgroundColor: '#6358ee10',
  },
  typeOptionText: {
    fontSize: 14,
    color: '#666',
  },
  typeOptionTextActive: {
    color: '#6358ee',
    fontWeight: '500',
  },
  textArea: {
    borderWidth: 1,
    borderColor: '#d9d9d9',
    borderRadius: 8,
    padding: 12,
    minHeight: 100,
    textAlignVertical: 'top',
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d9d9d9',
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#666',
    fontSize: 16,
    fontWeight: '500',
  },
  submitButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: '#6358ee',
    alignItems: 'center',
  },
  submitButtonDisabled: {
    opacity: 0.7,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
